# Numpy IV - 19/07

In [2]:
import numpy as np
import pandas as pd

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [11]:
np.random.seed(42)
array = np.random.random_sample((3,5))
array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [12]:
np.random.seed(42)
array_igual = np.random.random_sample((3,5))
array_igual

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

2. Cread los siguientes arrays:
   * Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
   * Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [13]:
array_uniforme = np.random.uniform(low = 0, high = 11, size = (2,3,5)).astype(int)
print(array_uniforme)
val_unicos_uniforme = np.unique(array_uniforme)
print(val_unicos_uniforme)

[[[ 2  3  5  4  3]
  [ 6  1  3  4  5]
  [ 8  2  5  6  0]]

 [[ 6  1  0 10 10]
  [ 8  3  1  7  4]
  [ 1  5  0 10  2]]]
[ 0  1  2  3  4  5  6  7  8 10]


In [14]:
array_binomial = np.random.binomial(10, 0.3, size = (2,3,5))
print(array_binomial)
val_unicos_binomial = np.unique(array_binomial)
print(val_unicos_binomial)

[[[4 2 3 3 2]
  [6 4 5 5 3]
  [5 1 2 1 2]]

 [[3 2 4 2 2]
  [3 1 4 1 6]
  [4 2 0 4 4]]]
[0 1 2 3 4 5 6]


3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
   * Elementos comunes entre los dos arrays
   * Unión de los dos arrays
   * ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [15]:
elem_comunes = np.intersect1d(val_unicos_uniforme, val_unicos_binomial)
elem_comunes

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
elem_union = np.union1d(val_unicos_uniforme, val_unicos_binomial)
elem_union

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [17]:
elem_val_uniforme = np.setdiff1d(val_unicos_uniforme, val_unicos_binomial)
elem_val_uniforme

array([ 7,  8, 10])

En el primer output encontramos todos los valos que tienen en común los dos arrays (val_unicos_uniforme, val_unicos_binomial).
En el segundo output vemos de forma ordenada en un array los elementos resultantes de juntar los arrays indicados (val_unicos_uniforme, val_unicos_binomial).
En el tercer array observamos los valores únicos que están en el primer array (val_unicos_uniforme) y no en el segundo (val_unicos_binomial).

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
   * Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
   * Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
   * Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
   * Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
   * ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [19]:
array1 = np.random.randint(1,100, (80))
print(array1)
print(".............................")
array2 = np.random.randint(1,100, (80))
print(array2)

[50 23 31 94 42 99  7 16 90 60  2  1 48 12 69 37 32  9 99 19 48 80  3 20
 24 54 33 24 75 72 36 38 84 99 89 99 25 93 18 82 66 54 35 80 61 41 33 68
 33 14 21 48 20  8  7 67 17 33 48 76 59 86 22 30 38 51 54  8 27 27 98 21
 30 97 28 64 97 69 61 48]
.............................
[19  4 35 64 49 17 44 92 30 93 46  6 99 37 24 93 46 53 95 99 60 97 63 85
 32 87 33 67 18 25 95 54 58 67 46 24 32 47 86 23 66 27  2 90 17 33  9 43
 48 39 93 42 26 99 50 25 24 13 60  7 57 36 45 20 65  8 16 14 76 87 15 92
 98 66 32 87 63 86 51 25]


In [21]:
val_unicos_array1 = np.unique(array1)
print(val_unicos_array1)
print("----------------")
val_unicos_array2 = np.unique(array1)
print(val_unicos_array2)

[ 1  2  3  7  8  9 12 14 16 17 18 19 20 21 22 23 24 25 27 28 30 31 32 33
 35 36 37 38 41 42 48 50 51 54 59 60 61 64 66 67 68 69 72 75 76 80 82 84
 86 89 90 93 94 97 98 99]
----------------
[ 1  2  3  7  8  9 12 14 16 17 18 19 20 21 22 23 24 25 27 28 30 31 32 33
 35 36 37 38 41 42 48 50 51 54 59 60 61 64 66 67 68 69 72 75 76 80 82 84
 86 89 90 93 94 97 98 99]


In [23]:
array3 = np.setdiff1d(array1, array2)
print(array3)

[ 1  3 12 21 22 28 31 38 41 59 61 68 69 72 75 80 82 84 89 94]


In [24]:
array4 = np.setdiff1d(array2, array1)
print(array4)

[ 4  6 13 15 26 39 43 44 45 46 47 49 53 57 58 63 65 85 87 92 95]


In [25]:
array5 = np.intersect1d(array1, array2)
print(array5)

[ 2  7  8  9 14 16 17 18 19 20 23 24 25 27 30 32 33 35 36 37 42 48 50 51
 54 60 64 66 67 76 86 90 93 97 98 99]


In [32]:
print("Los elementos presentes en ambos arrays son", len(array5))
print("Los elementos presentes en el array1 y no en el array2 son", len(array3))
print("Los elementos presentes en el array2 y no en el array1 son", len(array4))
print("Los elementos repetidos en el array1 son", len(array1) - len(array3) - len(array5))
print("Los elementos repetidos en el array2 son", len(array2) - len(array4) - len(array5))

Los elementos presentes en ambos arrays son 36
Los elementos presentes en el array1 y no en el array2 son 20
Los elementos presentes en el array2 y no en el array1 son 21
Los elementos repetidos en el array1 son 24
Los elementos repetidos en el array2 son 23


In [34]:
(len(array1) - len(array3) - len(array5)) + len(array3) + len(array5) == (len(array2) - len(array4) - len(array5)) + len(array4) + len(array5)

True