# Numpy III - 18/07

In [1]:
import numpy as np
import pandas as pd

1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [3]:
array = np.random.rand(2,3,5).round(1)
print(array)

[[[0.4 0.2 0.3 0.3 0.4]
  [0.6 0.1 0.8 0.2 0.4]
  [0.6 0.6 0.8 0.3 0. ]]

 [[0.3 0.4 0.7 0.8 0.6]
  [0.4 0.2 0.5 0.4 0.2]
  [0.  0.6 0.5 0.7 0.8]]]


2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
media = np.mean(array).round(1)
media

0.4

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
maximo = np.max(array).round(1)
maximo

0.8

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
minimo = np.min(array).round(1)
minimo

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
    * Si el valor del array es igual que la media, se reemplaza por "A".

    * Si el valor del array es mayor que la media, se reemplaza por "B".

    * Si el valor del array es menor que la media, se reemplaza por "C".

    * Si el valor es igual que el máximo, se reemplaza por "D".

    * Si el valor es igual que el mínimo, se reemplaza por "E".

In [9]:
array_vacio = np.empty_like(array, dtype =str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [10]:
array.shape

(2, 3, 5)

In [11]:
array.shape[0]

2

In [17]:
for x in range(array.shape[0]):
  
    for y in range(array.shape[1]):
    
        for z in range(array.shape[2]):
          
            if array[x,y,z] == media:
                array_vacio[x,y,z] = "A"
            elif array[x,y,z] > media:
                array_vacio[x,y,z] = "B"
            elif array[x,y,z] < media:
                array_vacio[x,y,z] = "C"
            elif array[x,y,z] == maximo:
                array_vacio[x,y,z] = "D"
            elif array[x,y,z] == minimo:
                array_vacio[x,y,z] = "E"

print(array_vacio)

[[['A' 'C' 'C' 'C' 'A']
  ['B' 'C' 'B' 'C' 'A']
  ['B' 'B' 'B' 'C' 'C']]

 [['C' 'A' 'B' 'B' 'B']
  ['A' 'C' 'B' 'A' 'C']
  ['C' 'B' 'B' 'B' 'B']]]


6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
   * Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1

    * Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2

    * Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [19]:
array_vacio2 = np.empty((30), dtype = int)
print(array_vacio2)

[4600877379321698714 4596373779694328218 4599075939470750515
 4599075939470750515 4600877379321698714 4603579539098121011
 4591870180066957722 4605380978949069210 4596373779694328218
 4600877379321698714 4603579539098121011 4603579539098121011
 4605380978949069210 4599075939470750515                   0
 4599075939470750515 4600877379321698714 4604480259023595110
 4605380978949069210 4603579539098121011 4600877379321698714
 4596373779694328218 4602678819172646912 4600877379321698714
 4596373779694328218                   0 4603579539098121011
 4602678819172646912 4604480259023595110 4605380978949069210]


In [20]:
indice = 0 

for x in range(array_vacio.shape[0]):
  
    for y in range(array_vacio.shape[1]):
    
        for z in range(array_vacio.shape[2]):
          
            if array_vacio[x,y,z] == "A" or array_vacio[x,y,z] == "B":
                array_vacio2[indice] = 1
                indice +=1
            elif array_vacio[x,y,z] == "C" or array_vacio[x,y,z] == "D":
                array_vacio2[indice] = 2
                indice +=1
            elif array_vacio[x,y,z] == "E":
                array_vacio2[indice] = 3
                indice +=1

array_final = array_vacio2.reshape(2,3,5)
print(array_final)
            

[[[1 2 2 2 1]
  [1 2 1 2 1]
  [1 1 1 2 2]]

 [[2 1 1 1 1]
  [1 2 1 1 2]
  [2 1 1 1 1]]]


In [21]:
# Otra forma:
array_vacio3 = np.empty((30), dtype = int)
print(array_vacio3)

[       60573056               0 140714277207216 140715330938608
 140714277204080 140715330938672 140714277192688 140715330938608
 140714277202288 140715330938672 140714277196720 140715331771248
 140715330938608 140715331771184 140714277204400 140715330938672
 140714277195568 140715330938608 140714277196272 140715330938672
 140714277193200 140715330938608 140714277207088 140715330938672
 140714277194096 140715330938608 140714277194992 140715330938672
 140714277207280 140715330938608]


In [22]:
indice = 0 

for subarray in array_vacio:
    for fila in subarray:
        for elemento in fila:
            if elemento == "A" or elemento == "B":
                array_vacio3[indice] = 1
                indice +=1
            elif elemento == "C" or elemento == "D":
                array_vacio3[indice] = 2
                indice +=1
            elif elemento == "E":
                array_vacio3[indice] = 3
                indice +=1

array_final2 = array_vacio3.reshape(2,3,5)
print(array_final2)

[[[1 2 2 2 1]
  [1 2 1 2 1]
  [1 1 1 2 2]]

 [[2 1 1 1 1]
  [1 2 1 1 2]
  [2 1 1 1 1]]]
