# Numpy II - 17/07

In [1]:
import numpy as np
import pandas as pd

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
   
    * El valor de la primera fila y la segunda columna.
    * Los valores de la segunda fila y las dos primeras columnas.
    * Extraed las filas pares (incluyendo la 0) y todas las columnas.
    * Extraed los valores que sean mayores que 0.5.
    * Extraed los valores menores que 0.2 o mayores que 0.5

In [5]:
array1 = np.random.random_sample((5,3)).round(2)
print(array1)

[[0.27 0.16 0.88]
 [0.54 0.77 0.85]
 [0.38 0.34 0.61]
 [0.64 0.81 0.41]
 [0.17 0.69 0.41]]


In [6]:
print(array1[0,1])
print("....................")
print(array1[1,:2])
print("....................")
print(array1[::2,:])
print("....................")
print(array1[array1 > 0.5])
print("....................")
cond1 = array1 < 0.2
cond2 = array1 > 0.5
print(array1[cond1 |cond2])

0.16
....................
[0.54 0.77]
....................
[[0.27 0.16 0.88]
 [0.38 0.34 0.61]
 [0.17 0.69 0.41]]
....................
[0.88 0.54 0.77 0.85 0.61 0.64 0.81 0.69]
....................
[0.16 0.88 0.54 0.77 0.85 0.61 0.64 0.81 0.17 0.69]


2. Cread dos array de tres dimensiones:
   
   * El primero de 2 matrices, 5 filas y 3 columnas.
   * El segundo de 3 matrices, 2 filas y 5 columnas
   * Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
   * Sumad los dos arrays. ¿Podéis? ¿Por qué?
   * Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
       * .reshape()
       * .transpose()
   * Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [8]:
array2 = np.random.randint(0,100, (2,5,3))
array3 = np.random.randint(0,100, (3,2,5))
print(array2)
print("..................")
print(array3)

[[[88  2 63]
  [86 60 32]
  [72  0 90]
  [34 84 94]
  [39 44 31]]

 [[92  3 92]
  [25 70 17]
  [82 52 64]
  [45  1 99]
  [27 95 17]]]
..................
[[[30 79 24 61 98]
  [39 14  9 49 33]]

 [[39 80 23 27 39]
  [24 30 77 28 24]]

 [[80 25 77 41 66]
  [58 69 26 15 29]]]


In [9]:
def propiedades(array):
    """
   Esta función printea en pantalla todas las propiedades del array.
  Args: 
       array(array): el array del cual queremos saber sus propiedades.
   Returns: aunque no tiene return, esta printea en pantalla todas las propiedades del array.
   """
    print("El tamaño es", array.size)
    print("La forma es", array.shape)
    print("La dimension es", array.ndim)
    print("El tipo de dato es", array.dtype)

In [10]:
propiedades(array2)

El tamaño es 30
La forma es (2, 5, 3)
La dimension es 3
El tipo de dato es int64


In [11]:
propiedades(array3)

El tamaño es 30
La forma es (3, 2, 5)
La dimension es 3
El tipo de dato es int64


In [12]:
array2 + array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No se pueden sumar estos dos arrays porque tienen distinta forma; tendrían que tener mismo número de elementos, filas y columnas.

In [13]:
array2_cambiado = np.transpose(array2,(1,2,0))
array3_cambiado = np.reshape(array3,(5,3,2))

In [14]:
array2_cambiado + array3_cambiado

array([[[118, 171],
        [ 26,  64],
        [161, 131]],

       [[100,  34],
        [109, 103],
        [ 71,  97]],

       [[ 95, 109],
        [ 39,  76],
        [120, 141]],

       [[ 62,  69],
        [164,  26],
        [171, 140]],

       [[105,  85],
        [113, 121],
        [ 46,  46]]])

In [16]:
array2_cambiado - array3_cambiado

array([[[ 58,  13],
        [-22, -58],
        [-35,  53]],

       [[ 72,  16],
        [ 11,  37],
        [ -7, -63]],

       [[ 49,  55],
        [-39,  28],
        [ 60, -13]],

       [[  6,  21],
        [  4, -24],
        [ 17,  58]],

       [[-27, -31],
        [-25,  69],
        [ 16, -12]]])