# Numpy I - 14/07

Happy coding 😀

Empezamos nuevo bloque de ejercicios de pair programming de NumPy.

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

    📌 Nota

   * El array de 2 dimensiones debe ser de 2 filas y 3 columnas

   * El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
import numpy as np

In [5]:
# unidimensional
a1 = np.arange(0,10,3)
print(a1)

#bidimensional
a2 = np.random.randint(0,100, (2,3))
print(a2)

#tridimensional
a3 = np.random.randint(0,100, (2,3,5))
print(a3)

[0 3 6 9]
[[14 80 55]
 [85 20 26]]
[[[60 93 23 71  6]
  [ 4 63  2 91 36]
  [11 45 66 50 32]]

 [[54 60 79 43 47]
  [33 35  0 16 11]
  [81 37 60 35 46]]]


2. Chequed las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [6]:
def propiedades(array):
    """
   Esta función printea en pantalla todas las propiedades del array.
  Args: 
       array(array): el array del cual queremos saber sus propiedades.
   Returns: aunque no tiene return, esta printea en pantalla todas las propiedades del array.
   """
    print("El tamaño es", array.size)
    print("La forma es", array.shape)
    print("El número de dimensiones es de", array.ndim)
    print("El tipo de dato es", array.dtype)

    

In [7]:
propiedades (a1)

El tamaño es 4
La forma es (4,)
El número de dimensiones es de 1
El tipo de dato es int64


In [8]:
propiedades (a2)

El tamaño es 6
La forma es (2, 3)
El número de dimensiones es de 2
El tipo de dato es int64


In [9]:
propiedades (a3)

El tamaño es 30
La forma es (2, 3, 5)
El número de dimensiones es de 3
El tipo de dato es int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [10]:
a4 =np.identity(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [12]:
a5 = np.ones_like(a3)
a5

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays
* ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
* En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
* Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
* Dividid las dos matrices

In [13]:
a2 + a4

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

No se puede porque no tiene las mismas filas y columnas.

In [19]:
a6 = np.random.randint(0,100, (3,3))
a6

array([[90, 34, 19],
       [20, 69, 32],
       [74, 41, 66]])

In [21]:
a6 + a4

array([[91., 34., 19.],
       [20., 70., 32.],
       [74., 41., 67.]])

In [23]:
np.add(a4,a6)

array([[91., 34., 19.],
       [20., 70., 32.],
       [74., 41., 67.]])

In [20]:
a6 * a4

array([[90.,  0.,  0.],
       [ 0., 69.,  0.],
       [ 0.,  0., 66.]])

In [24]:
np.multiply(a4,a6)

array([[90.,  0.,  0.],
       [ 0., 69.,  0.],
       [ 0.,  0., 66.]])

In [22]:
a4 / a6

array([[0.01111111, 0.        , 0.        ],
       [0.        , 0.01449275, 0.        ],
       [0.        , 0.        , 0.01515152]])

In [26]:
np.divide(a4,a6)

array([[0.01111111, 0.        , 0.        ],
       [0.        , 0.01449275, 0.        ],
       [0.        , 0.        , 0.01515152]])